
spring:
  application:
    name: rabbitmq-ack-message
  rabbitmq:
    host: 49.235.231.176
    username: guest
    password: guest
    virtual-host: vh01
    port: 5672
    # 生产方配置
    publisher-confirms: true
    publisher-returns: true
    # listener 监听者 消费方配置
    listener:
      simple:
        # 手动确认消息被消费
        acknowledge-mode: manual
        # 并发消费者初始化值
        retry:
          enabled: true
          max-attempts: 1
        concurrency: 1 # 指定最小消费者数量
        max-concurrency: 1 # 指定最大消费者数量
      direct:
        acknowledge-mode: manual




